### PR TITLE
remove return statement from console.log

### PR DESCRIPTION
**Pull request by tavelli**
causes compilation failure when using typescript

### CODE REVIEW

**Comment by tavelli** [comment]
i signed it

**Comment by nicolasgarnier** [comment]
@tavelli Could you tell us a little more about the error that you are seeing with Typescript? (e.g. could you paste the error here?)

We added an ESLint rule to all projects that makes having a return statement inside promises mandatory to avoid some common errors that developer face when writing these return promises (e.g. forgetting to return a Promise or a chained/sub promise).

cc/ @inlined @tinaliang

**Comment by nicolasgarnier** [comment]
FYI we added this as part of #306

**Comment by tavelli** [comment]
@nicolasgarnier my bad i's actually tslint error not compile error, but it will cause deploy firebase deploy to fail if using default tslint config created during firebase init. 

the lint error is: 
ERROR: Expression has type `void`. Put it on its own line as a statement.

so it can also resolved by just moving return statement onto separate line after the console.log

```
return streamAsPromise.then(() => {
    console.log('Thumbnail created successfully');
    return;
})
```

**Comment by inlined** [comment]
That looks good to me. I'd also accept inlined expressions as well (they're exempt from the always-return linter rule):

```
return streamAsPromise
    .then(() => console.log('Thumbnail created successfully'))
    .catch(err => console.error('Error creating thumbnail', err));
```

As some minor other fixes from my sample: always print your errors and print them to stderr.

**Comment by nicolasgarnier** [comment]
I just added the `return null;` to  your PR. Let's merge!

Thanks @tavelli !

**Comment by tavelli** [comment]
Thanks!

**Pull request merged**
