### PR TITLE
Exif function example, fix "not defined" errors.

### PR DESCRIPTION
**Pull request by sefk**
This example has been broken since this pull request on Feb 2018:
https://github.com/firebase/functions-samples/pull/306/files. Fixes "result not
defined" and "metadata not defined" errors but the overall control flow was
also pretty broken.

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
@sefk Thanks for the fix! I'll change this a bit since we need to follow a strict styling on this repo now and nested Promises are not allowed (which caused the original error to begin with).

@samtstern any idea why the travis build passed? I do see the ESLint errors in there

**Comment by sefk** [comment]
Thanks for taking a look, @nicolasgarnier. Changed to unnest promises. Not sure if the state passing in line 57-58 is the best way to do that, feels kinda clunky.

Also glad that you're following up on why our automated tests didn't catch. Maybe other similar problems were introduced in [that same pull request](https://github.com/firebase/functions-samples/pull/306)?

**Comment by nicolasgarnier** [comment]
Thanks for this @sefk ! Just tweaked it a bit (we need to return the `admin.database()...` promise to make sure the async jobs are chained) and also we enforce returning in every promise to avoid the mistake where developer forget to return Promises which result un functions terminating too early.

**Comment by sefk** [comment]
Appreciate the cleanups! Thanks.

**Pull request merged**
