### PR TITLE
Add sample demonstrating Google Sheet Sync

### PR DESCRIPTION
**Pull request by elon-gs**

### CODE REVIEW

**Comment by elon-gs** [comment]
I signed it!

**Comment by elon-gs** [comment]
@nicolasgarnier Just checking in on this

**Comment by elon-gs** [comment]
No problem — done.

**Comment by puf** [comment]
Very cool integration.

**Comment by elon-gs** [comment]
@nicolasgarnier Anything else you'd like changed?

**Comment by elon-gs** [comment]
@nicolasgarnier Checking again…

**Comment by nicolasgarnier** [comment]
Sorry for the delay! checking now :)

**Comment by nicolasgarnier** [comment]
All right! LGTM, I updated the instructions in the README to match the latest code and did a bit of cleanup. i also am now using mappings to Firebase hosting (so you can use YOUR-APP-ID.firebaseapp.com/functionName). Merging :)

**Comment by nicolasgarnier** [comment]
Thanks for the work @elon-gs  :)

**Pull request merged**
