### PR TITLE
Removes usage of @google-cloud/firestore

### PR DESCRIPTION
**Pull request by abehaskins**
Removes old snippet which uses `@google-cloud/firebase`

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
fulltext-search-firestore and quickstart/uppercaser-firestore also import @google-cloud/firebase could you premove it from there too?

Also can you remove the import in package.json ? (in all 3 samples)

**Comment by abehaskins** [comment]
Are you sure? I don't see them importing it, however it is in the package.json and I'll fix that.

**Comment by nicolasgarnier** [comment]
Yup I think it's just in the 3 package.json :)

**Comment by abehaskins** [comment]
Okay, removed!

**Comment by nicolasgarnier** [comment]
Looks good!

**Pull request merged**
