### PR TITLE
README.md changed to gender-neutral pronouns

### PR DESCRIPTION
**Pull request by XenioxYT**
Changed 'him' to 'them' in README.md, which is more gender neutral.

### CODE REVIEW

**Review by jhuleatt — APPROVED** [review]

**Comment by jhuleatt** [comment]
Much appreciated, @XenioxYT! Just need you to sign a CLA as described by the bot, and then we can merge.

**Comment by XenioxYT** [comment]
> Much appreciated, @XenioxYT! Just need you to sign a CLA as described by the bot, and then we can merge. 

No worries; will get that done now.

**Comment by XenioxYT** [comment]
All done ✅

**Comment by jhuleatt** [comment]
Thanks for making this sample more inclusive, @XenioxYT!

**Comment by shauryaaher** [comment]
Great work.

```JavaScript
console.log("Good job 🤙");
```

**Comment by Bokkieboy** [comment]
Hahaha virgin

**Pull request merged**
