### PR TITLE
CREATE with-firebase-hosting-and-docker example

### PR DESCRIPTION
**Pull request by sarovin**
Adds an example based off of @jthegedus work on firebase hosting, compatible with next v7 and using docker for deploy, dev and serve.

### CODE REVIEW

**Comment by sarovin** [comment]
signed

**Comment by sarovin** [comment]
I signed it!

**Comment by jthegedus** [comment]
@sarovin https://github.com/zeit/next.js/pull/5373#discussion_r222508172

**Comment by Bolket** [comment]
I signed it!

**Comment by jhuleatt** [comment]
Hey @Bolket, sorry we never took a look at this PR! Since it looks like it was accepted into the Next.js repo, I'm going to close this.

**Pull request closed without merging**
