### PR TITLE
Add YouTube sample

### PR DESCRIPTION
**Pull request by jhuleatt**
Inspired by #781 and @akhromieiev's excellent [blog post](https://akhromieiev.com/get-the-latest-video-of-a-youtube-channel-using-cloud-functions-for-firebase/)!

### CODE REVIEW

**Review by akhromieiev — APPROVED** [review]
LGTM
I like it! @jhuleatt

**Comment by jhuleatt** [comment]
Thanks for the review @akhromieiev! You can see in the [commit](https://github.com/firebase/functions-samples/commit/a49e08ecf6d8dd9707b5398ebe7ba09625f7340e) that we share the authorship credit

**Comment by akhromieiev** [comment]
> Thanks for the review @akhromieiev! You can see in the [commit](https://github.com/firebase/functions-samples/commit/a49e08ecf6d8dd9707b5398ebe7ba09625f7340e) that we share the authorship credit

Cool! My first co-contribution to Firebase 🎉
Thanks for your help!

BTW, Other blog posts related to cloud functions are coming soon. I will try to contribute more.

**Comment by jhuleatt** [comment]
That's great to hear! If you're interested in cross-publishing any Firebase posts to our Medium audience, we'd definitely be interested. Here are the instructions for that: https://medium.com/firebase-developers/write-for-us-66032505ed8b

**Pull request merged**
